In [1]:
import polars as pl

csv_file = "/home/andrew/notebook/2025-10-29/peeking_at_roberts_files/mawa-unified_datafile-Pittsburg_mouse_liver_TLS_slide-20251008_095157_EDT_standardized_phenotypes.csv"

lf = pl.scan_csv(csv_file)

In [2]:
lf.head().collect()

shape: (5, 24)
┌───────────┬────────────┬────────────┬───────┬───┬────────────┬───────────┬───────────┬───────────┐
│ Sample_ID ┆ Centroid X ┆ Centroid Y ┆ XMax  ┆ … ┆ Phenotype_ ┆ Phenotype ┆ Phenotype ┆ Phenotype │
│ ---       ┆ (µm)_(stan ┆ (µm)_(stan ┆ ---   ┆   ┆ (standardi ┆ _(standar ┆ _(standar ┆ _(standar │
│ str       ┆ dardized)  ┆ dardized)  ┆ i64   ┆   ┆ zed) CD19  ┆ dized)    ┆ dized)    ┆ dized)    │
│           ┆ ---        ┆ ---        ┆       ┆   ┆ ---        ┆ MHCII     ┆ NOS2      ┆ COX2      │
│           ┆ f64        ┆ f64        ┆       ┆   ┆ i64        ┆ ---       ┆ ---       ┆ ---       │
│           ┆            ┆            ┆       ┆   ┆            ┆ i64       ┆ i64       ┆ i64       │
╞═══════════╪════════════╪════════════╪═══════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ MS_01     ┆ 6209.2     ┆ 14274.2    ┆ 19113 ┆ … ┆ 0          ┆ 1         ┆ 0         ┆ 0         │
│ MS_01     ┆ 6201.8     ┆ 14283.2    ┆ 19100 ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
│ MS_01     ┆ 6174.4     ┆ 14288.8    ┆ 19007 ┆ … ┆ 0          ┆ 1         ┆ 0         ┆ 0         │
│ MS_01     ┆ 6191.8     ┆ 14290.0    ┆ 19058 ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
│ MS_01     ┆ 6179.4     ┆ 14288.4    ┆ 19018 ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 0         │
└───────────┴────────────┴────────────┴───────┴───┴────────────┴───────────┴───────────┴───────────┘

In [2]:
image_col = "Image ID_(standardized)"

images_of_interest = ["MS_01_1400w", "MS_01_cele_1400w"]

lf_two_images = lf.filter(pl.col(image_col).is_in(images_of_interest))

marker_cols_with_prefix = [col for col in lf_two_images.collect_schema().names() if col.startswith("Phenotype_(standardized) ")]

print(marker_cols_with_prefix)

['Phenotype_(standardized) CD4', 'Phenotype_(standardized) CD8a', 'Phenotype_(standardized) CD11c', 'Phenotype_(standardized) CD19', 'Phenotype_(standardized) MHCII', 'Phenotype_(standardized) NOS2', 'Phenotype_(standardized) COX2']

2025-12-11 01:04:36.613 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:04:37.250 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:04:37.250 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:04:37.251 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:04:37.251 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:04:37.252 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:04:37.252 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:04:37.253 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:04:37.254 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:04:37.254 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:04:37.255 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:04:37.256 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

Final number of rows: 1179345 == total marker 1s: 1179345

In [11]:
lf_pheno.filter(pl.col(image_col) == images_of_interest[1]).select(pl.len()).collect()

shape: (1, 1)
┌────────┐
│ len    │
│ ---    │
│ u32    │
╞════════╡
│ 780066 │
└────────┘

In [18]:
lf_pheno.head().collect()

shape: (5, 4)
┌─────────────┬────────┬─────────┬─────────┐
│ TMA_core_id ┆ Xcor   ┆ Ycor    ┆ Lineage │
│ ---         ┆ ---    ┆ ---     ┆ ---     │
│ str         ┆ f64    ┆ f64     ┆ str     │
╞═════════════╪════════╪═════════╪═════════╡
│ MS_01_1400w ┆ 6636.8 ┆ 10392.4 ┆ MHCII   │
│ MS_01_1400w ┆ 3093.6 ┆ 6187.0  ┆ CD4     │
│ MS_01_1400w ┆ 3093.6 ┆ 6191.0  ┆ CD4     │
│ MS_01_1400w ┆ 3093.2 ┆ 6194.4  ┆ CD4     │
│ MS_01_1400w ┆ 3093.4 ┆ 6198.2  ┆ CD4     │
└─────────────┴────────┴─────────┴─────────┘

In [3]:
from fast_neighborhood_profiles import main as fnp_main

lf_pheno = fnp_main.perform_marker_phenotyping_on_lazyframe(lf_two_images, marker_cols_with_prefix)

lf_pheno = lf_pheno.filter(pl.col(image_col) == images_of_interest[0]).rename({"Image ID_(standardized)": "TMA_core_id", "Centroid X (µm)_(standardized)": "Xcor", "Centroid Y (µm)_(standardized)": "Ycor", "label": "Lineage"}).select(pl.col(["TMA_core_id", "Xcor", "Ycor", "Lineage"])).sort(by="TMA_core_id")

2025-12-11 01:43:06.363 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:43:06.364 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:43:06.364 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:43:06.462 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:43:06.696 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:43:06.697 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:43:06.698 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:43:06.698 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:43:06.699 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:43:06.699 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:43:06.700 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:43:06.700 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:43:06.701 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:43:06.701 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:43:06.702 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

Final number of rows: 1179345 == total marker 1s: 1179345

In [7]:
import pandas as pd
import importlib
from fast_neighborhood_profiles import SpatialUMAP
import numpy as np
importlib.reload(SpatialUMAP)

spatial_umap = SpatialUMAP.SpatialUMAP(np.array([25, 50, 100, 150, 200]), 1, 0.2)

# I don't want to, but convert to pandas for compatibility with SpatialUMAP class.
spatial_umap.cells = lf_pheno.collect().to_pandas()

# Set explicitly as numpy array the cell coordinates (x, y).
spatial_umap.cell_positions = spatial_umap.cells[['Xcor', 'Ycor']].values

# Set explicitly as one hot data frame the cell labels.
spatial_umap.cell_labels = pd.get_dummies(spatial_umap.cells['Lineage'])

# Set the region is to be analyzed (a TMA core is treated similar to a region of a interest).
spatial_umap.region_ids = spatial_umap.cells.TMA_core_id.unique()

# Clear metrics.
spatial_umap.clear_counts()
spatial_umap.clear_areas()

unique_labels = [x.removeprefix("Phenotype_(standardized) ") for x in marker_cols_with_prefix]

# Save the unique labels/lineages/species. This is only used for Andrew's counting method.
spatial_umap.species = unique_labels

# Determine which counting method to use based on the input parameter. Note I have shown that the methods precisely agree.
spatial_umap.get_counts_And(cpu_pool_size=1, mp_start_method="forkserver")

Using start method forkserver with 1 CPUs.

2025-12-11 01:50:20.694 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:50:20.694 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:50:20.694 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:50:20.782 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:50:21.221 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:50:21.221 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:50:21.221 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:50:21.221 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:50:21.221 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:50:21.221 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:50:21.222 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:50:21.222 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:50:21.222 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:50:21.222 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-12-11 01:50:21.222 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

Calculating neighbor counts for image MS_01_1400w (399279 cells) using the new kdtree method 20000...
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA MS_01_1400w
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB MS_01_1400w
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC MS_01_1400w
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDD MS_01_1400w
  ...finished calculating neighbor counts for image MS_01_1400w (399279 cells) in 89.49 seconds